CREATE TABLE IF NOT EXISTS contrato (

    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    razãoSocialContratada varchar(250),
    nomeFantasiaContratada varchar(250),
    CNPJContratada varchar(9),
    logradouroContratada varchar(200),
    bairroContratada varchar(100),
    cidadeContratada varchar(120),
    estadoContratada varchar(2),
    cepContratada varchar(8),
    faturamentoContratada float,
    numeroLojas int,
    razãoSocialContratante varchar(250),
    nomeFantasiaContratante varchar(250),
    CNPJContratante varchar(9),
    logradouroContratante varchar(200),
    bairroContratante varchar(100),
    cidadeContratante varchar(120),
    estadoContratante varchar(2),
    cepContratante varchar(8),
    dataAbertura DATE,
    dataTermino DATE,
    valor float,
    numeroParcelas int,
    DiaVencimentoParcela int,
    valorParcela float,
    valorParcelaLoja float);